### ISSUE TITLE
ArboryImage resize fails when original image extension ir required

### ISSUE THREAD

**Issue by mungurs** [arbory/arbory#10]
If I need to get image URL in original file format using this glide preset 
```php
    'presets' => [
        'small' => [
            'w' => 200,
            'h' => 200
        ],
    ],
```
glide will throw exception which gets silenced in ArboryImage getUrl method.

Problem lies in fact, that glide uses pathinfo to determine original extension, but uploaded files are hash without extension.  
In glide/src/Server.php getCachePath method
```php
if ($this->cacheWithFileExtensions) {
            $ext = (isset($params['fm']) ? $params['fm'] : pathinfo($path)['extension']);
            $ext = ($ext === 'pjpg') ? 'jpg' : $ext;
            $cachedPath .= '.'.$ext;
        }
```

**Comment by strads10** [comment]
Should be resolved with 980c385f5bb625185f910894ea640d8dd52fc84f
