### ISSUE TITLE
Can't create Sortable ArboryImage

### ISSUE THREAD

**Issue by mungurs** [arbory/arbory#11]
```php
$fieldSet->add( new Sortable( 'position',  new HasMany('partner_images', function (FieldSet $fieldSet) {
           $fieldSet->add( new Hidden('field_name'))->setValue('partner_images');
           $fieldSet->add( new ArboryImage( 'file' ) )->rules( 'arbory_file_required' );
        })));
```
If i try to save this structure in pages form, I will receive exception:
![image](https://user-images.githubusercontent.com/3380457/30206864-254de4c6-9496-11e7-881f-41565f27760a.png)

Looks like fieldset is null in partner_images field and I cant find reason why its not getting set.

If I remove Sortable or ArboryImage from structure everything will work fine.

**Comment by strads10** [comment]
Fixed in 5f49fa530ac6a8277c25b2e15b1e834de67dc7e6
