### ISSUE TITLE
Key length error, when trying to install

### ISSUE THREAD

**Issue by EinarsBistrovs** [arbory/arbory#127]
**Describe the bug**
Console returns this error when trying to install.
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
I tried setting the string length in appServiceProvider with Schema::defaultStringLength(191); 
Still receiving same error.

Laravel 5.5
PHP 7.2
Mysql 5.7.24
Wamp server Apache 2.4.37

**Comment by eddyonboard** [comment]
Try to add `'engine'=>'INNODB'` option to your config/database.php under _connection->mysql_ configuration.
