### ISSUE TITLE
roave/security-advisories package fails to install

### ISSUE THREAD

**Issue by holystix** [arbory/arbory#13]
After creating a new laravel project, `composer require arbory/arbory dev-master` fails to install with the following error reported by composer:

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for arbory/arbory dev-master -> satisfiable by arbory/arbory[dev-master].
    - arbory/arbory dev-master requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

If roave/security-advisories is installed separately with dev-master version, arbory install can then be completed as normal.

**Comment by strads10** [comment]
`mimimum-stability` needs to be set to `dev`

Updated readme in ccc9ece724a8fd953b8d570076d341810e03e458, to reflect this
