### ISSUE TITLE
ArboryFile : Identical files are stored without extension

### ISSUE THREAD

**Issue by mungurs** [arbory/arbory#16]
ArboryFile's stored in files table are missing extension if file with the same content already exists.

![image](https://user-images.githubusercontent.com/3380457/31131634-5905283e-a863-11e7-8b54-b669e9f0ab35.png)

**Comment by holystix** [comment]
Seems to be aused by this:
https://github.com/holystix/arbory/blob/master/src/Repositories/ArboryFilesRepository.php#L135-L145

**Comment by holystix** [comment]
Fixed in https://github.com/arbory/arbory/pull/33
