### ISSUE TITLE
Generated Node slugs are not unique

### ISSUE THREAD

**Issue by holystix** [arbory/arbory#2]
It's possible to create multiple sibling nodes with the same slug. The rightmost node seems to have priority when accessing its URL.

**Comment by strads10** [comment]
Fixed slug generator creating duplicates 2ed7607a94545a643cc5bebd778a1888d0ae099c, but we still need a proper validation rule to disallow a node with a duplicate slug from being saved.

**Comment by mungurs** [comment]
Nodes parent id and slug should be unique in database.

**Comment by cliche23** [comment]
This is fixed only for child nodes. It is still possible to create nodes with the same slog in top level.
