### ISSUE TITLE
ArboryFile saving

### ISSUE THREAD

**Issue by ezitisitis** [arbory/arbory#205]
**Describe the bug**
When saving file in `file` field, file is saved but not showing. In field `No file selected`

**To Reproduce**
1. In admin controller which contains `file` field;
2. Add file;
3. Press `save`;
4. See that file is not saved (in UI, if check a DB and storage, file is saved);

**Expected behavior**
After save, saved file name expected.

**Real behavior**
After save, field is showing that it's empty

**Screenshots**
Before uploaded file
![Screenshot 2020-03-05 at 19 27 57](https://user-images.githubusercontent.com/6075434/76007969-8fd1cf80-5f17-11ea-82fd-2fa46f15ba04.png)

Uploaded file
![Screenshot 2020-03-05 at 19 28 04](https://user-images.githubusercontent.com/6075434/76008015-9f511880-5f17-11ea-9d7f-4e194d602b54.png)

After save
![Screenshot 2020-03-05 at 19 28 17](https://user-images.githubusercontent.com/6075434/76008028-a415cc80-5f17-11ea-8da8-203056428322.png)

**Additional context**
- Arbory: 1.0.x-dev
- PHP: 7.4.2

**Possible solution**
In project have fixed the issue with this:

Created new `ArboryFile` field:
```
<?php

namespace App\Admin\Form\Fields;

use Arbory\Base\Admin\Form\Fields\ArboryFile as BaseArboryFile;
use Arbory\Base\Admin\Form\Fields\Renderer\FileFieldRenderer;

class ArboryFile extends BaseArboryFile
{
    // Override correct renderer
    protected $rendererClass = FileFieldRenderer::class;
}
```

In Controller:
```
protected function form(Form $form)
    {
        $form->setFields(function (FieldSet $fields) {
           $fields->text('description');
           $fields->select('status')
               ->options(Feedback::STATUS_NAMES);
           $fields->add(new App\Admin\Form\Fields\ArboryFile('audioFile'));
        });

        return $form;
    }
```

**Comment by cliche23** [comment]
> 4. See error

What is the error?

**Comment by ezitisitis** [comment]
Changed:
**From:**
4. See error

**To**
4. See that file is not saved (in UI, if check a DB and storage, file is saved);

**Comment by jaaniskal** [comment]
**ArboryFile** has not set **$rendererClass**. It should be set to **FileFieldRenderer::class**. Otherwise it extends this variable from **ControlField** where it is set as **ControlFieldRenderer::class**. So **ArboryFile** renders the field wrong (in case where you have an uploaded file it does not show up).

**Comment by rerzy** [comment]
This has already been resolved in this commit: https://github.com/arbory/arbory/commit/f7c0bd817921242d6fd96fe89ae7bf5b00a339cb
