### ISSUE TITLE
Incorrect preview URL

### ISSUE THREAD

**Issue by janikaja** [arbory/arbory#236]
https://github.com/arbory/arbory/blob/9854d88702630150021aa251d97c9eae564e90bd/src/Admin/Form/Fields/Slug.php#L64
Value of $slugHashed variable is incorrect, if $urlToSlug starts with "/". All slashes should be removed beforehand.

**Comment by miks** [comment]
@janikaja can you make a pull request for this? Looks like 5 minutes job.
