### ISSUE TITLE
Upgrate to Laravel Mix 6

### ISSUE THREAD

**Issue by exabyssus** [arbory/arbory#273]
Currently used Laravel Mix v4.1.4 is outdated and limits ability to upgrade packages that have security vulnerabilities.
Existing [webpack.mix.js](https://github.com/arbory/arbory/blob/master/webpack.mix.js) file should be migrated to support Mix v6 and resulting assets tested.

**Comment by miks** [comment]
https://github.com/arbory/arbory/pull/285 made it
