### ISSUE TITLE
Link getAttribute method overrides Model

### ISSUE THREAD

**Issue by ubrize** [arbory/arbory#29]
When upgrading to Laravel 5.6 Arbory\Base\Links\Link.php is no longer working - it is overriding getAttributes method on Model, that is now used in getDirty - https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1043

**Comment by roboc** [comment]
Fixed in release 0.2.16
