### ISSUE TITLE
The generated Node slugs don't show the node's full path initially

### ISSUE THREAD

**Issue by janikaja** [arbory/arbory#4]
The generated Node slug doesn't show the node's full path initially (before saving), it just shows the hostname followed by two consequtive slashes "//" and the generated slug, and it's regardless of how deep the node actually resides in the nodes tree.

![image](https://user-images.githubusercontent.com/14277940/28607161-32f36978-71e3-11e7-915d-b0ba7c17b774.png)

**Comment by strads10** [comment]
Resolved in c5505640f534bec6aef3048991a5963353ca947e
