### ISSUE TITLE
Separate mix files

### ISSUE THREAD

**Issue by holystix** [arbory/arbory#7]
I suggest that the arbory:install script creates two separate webpack.mix files. One for admin assets, and one for frontend (which is much more likely to be modified per project needs).

For example:

**webpack.mix.js**
```
const { mix } = require( 'laravel-mix' );
const { env } = require( 'minimist' )( process.argv.slice( 2 ) );
if ( env && env.site ) {
    require( `${__dirname}/webpack.mix.${env.site}.js` );
}
```
**webpack.mix.admin.js**
```
let mix = require( 'laravel-mix' );

mix.webpackConfig( {
    resolve: {
        modules: [
            path.resolve( __dirname, './node_modules' ),
            path.resolve( __dirname, './vendor/arbory/arbory/resources/assets/js/' )
        ]
    }
} );

mix.js( 'resources/assets/js/admin.js', 'public/js' );
require( './vendor/arbory/arbory/webpack.mix' )( mix );
```
**webpack.mix.front.js**
```
let mix               = require( 'laravel-mix' );
let BrowserSyncPlugin = require( 'browser-sync-webpack-plugin' );

mix.webpackConfig( {
    plugins: [
        new BrowserSyncPlugin( {
            proxy : 'localhost',
            port  : 3000,
            open  : false,
            notify: false
        } )
    ]

} );

mix.ts( 'resources/assets/js/app.ts', 'js' )
    .sass( 'resources/assets/sass/app.scss', 'css' )
    .setPublicPath("public/front");
```

An additional benefit is reduced build times, as there is no need to compile all the admin assets if we only want to work on the frontend. To achieve this, separate npm scripts could be added to package.json for convenience, for example:
```
 "watch:front": "npm run watch -- --env.site=front",
 "watch:admin": "npm run watch -- --env.site=admin",
```

A caveat is that each script would overwrite each others mix-manifest.json, unless a custom path is specified for one or both of them via mix.setPublicPath.

**Comment by strads10** [comment]
Seems alright. The admin manifest could be stored in public/arbory.

But, do we really need a separate file for front? It would probably be better to put all the app asset logic in webpack.mix.js and then to conditionally call the webpack.mix.admin.js file when needed.

Or, alternatively, plain old webpack allows you to pass a --config parameter, if we could get something like that with mix, we could just keep the admin file completely seperate, and only call it on package updates.

**Comment by holystix** [comment]
Unfortunately mix does not support setting a custom webpack.mix file when executing webpack, so it seems the only option is to determine and load the appropriate mix configuration at runtime.

**Comment by holystix** [comment]
Added a PR to move this forward https://github.com/arbory/arbory/pull/18
