### ISSUE TITLE
Sortable items

### ISSUE THREAD

**Issue by danielsGrietins** [arbory/arbory#73]
**Is your feature request related to a problem? Please describe.**
You can sort model relation items but you cannot sort model entries by themself. 

**Describe the solution you'd like**
Sorting entries in model index view with drag and drop would be nice

**Comment by ezitisitis** [comment]
Is this still actual?

**Comment by cliche23** [comment]
Yes

**Comment by ezitisitis** [comment]
Just to make thinks clear- are we speaking about this view?

![image](https://user-images.githubusercontent.com/6075434/71959588-bf0bdf00-31fb-11ea-9fdc-2b40f1741e3e.png)

**Comment by cliche23** [comment]
Yes

**Comment by ezitisitis** [comment]
Okay, will do.
Will need it in one of my projects.
