### ISSUE TITLE
arbory.admin_auth middleware is always applied to custom admin.php routes

### ISSUE THREAD

**Issue by holystix** [arbory/arbory#97]
The middleware is applied to all routes within routes/admin.php here: https://github.com/arbory/arbory/blob/master/src/Providers/ArboryServiceProvider.php#L190-L208
   ``` 
private function registerAppRoutes()
    {
        $adminRoutes = base_path( 'routes/admin.php' );
        if( !File::exists( $adminRoutes ) )
        {
            return;
        }
        $this->app['router']->group( [
            'as' => 'admin.',
            'middleware' => [ 'admin', 'arbory.admin_auth' ],
            'namespace' => '',
            'prefix' => config( 'arbory.uri' )
        ],function () use ($adminRoutes)
        {
            include $adminRoutes;
        } );
    }
```

This complicates creating new admin routes that might not require authentication. One such scenario might be a different login route.

I propose removing the logic that applies 'arbory.admin_auth' middleware to all custom admin routes automatically, and instead apply it to `Routes::group`, similarly to how it is done in  https://github.com/arbory/arbory/blob/0.2.16/routes/admin.php#L7 
```
Route::group( [ 'middleware' => 'arbory.admin_auth' ], function ()
...
```

**Comment by exabyssus** [comment]
This would cause security problems if changed.
